on:
  schedule:
    - cron: '*/30 01 * * *'
  workflow_dispatch:

name: refresh-data


env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  refresh-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Cache packages
        uses: actions/cache@v3
        with:
            path: ${{ env.RENV_PATHS_ROOT }}
            key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
            restore-keys: |
                ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
            if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
            renv::restore()

      - name: Get data - TGP
        run: Rscript -e 'source(here::here("source", "go.R"), echo = TRUE)'
        
      - name: Commit
        run: |
          git config --global user.name 'Nick Twort'
          git config --global user.email 'nwbort@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"