on:
  schedule:
    - cron: '*/53 00 * * *'
  workflow_dispatch:

name: refresh-data


env:
  RENV_PATHS_ROOT: ~/.local/share/renv

jobs:
  refresh-data:
    runs-on: macOS-13
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true
          
      - name: Install vctrs
        run: Rscript -e 'install.packages(c("vctrs"))'

      - name: Install packages
        run: Rscript -e 'install.packages(c("tidyverse", "lubridate", "magrittr", "here", "janitor", "readxl", "rvest", "glue", "pdftools", "httr"))'

      - name: Get data - TGP
        run: Rscript -e 'source(here::here("source", "go.R"), echo = TRUE)'
        
      - name: Commit
        run: |
          git config --global user.name 'Nick Twort'
          git config --global user.email 'nwbort@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
