on:
  schedule:
    - cron: '*/30 01 * * *'
  workflow_dispatch:

name: refresh-data

jobs:
  refresh-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install vctrs
        run: Rscript -e 'install.packages(c("vctrs"))'

      - name: Install packages
        run: Rscript -e 'install.packages(c("tidyverse", "lubridate", "magrittr", "here", "janitor", "readxl"))'

      - name: Get data - TGP
        run: Rscript -e 'source(here::here("source", "TGP.R"), echo = TRUE)'
        
      - name: Commit
        run: |
          git config --global user.name 'Nick Twort'
          git config --global user.email 'nwbort@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"